proj_value_dict = {'projected': 'what is the projected to reach amount',
                   'estimated': 'what is the estimated amount',
                       'estimate': 'what is the estimate amount',
                       'increased': 'what is the increased amount',
                       'increase': 'what is the increase in amount',
                       'increasing': 'what is the increasing amount',
                       'surged': 'what is the surged amount',
                       'surge': 'what is the surge in amount',
                       'surging': 'what is the surging amount',
                       'expected': 'what is the expected amount',
                       'growing': 'what is the amount growing to',
                       'grew': 'how much has the amount grew to',
                       'grow': 'what will the amount grow to',
                       'expanded': 'what is the expanded amount',
                       'expand': 'what is the amount to expand',
                       'expanding': 'what is the expanding amount',
                       'reached': '<keyword> is reached in which year',
                     'reaching': '<keyword> will be reaching in which year',
                     'reach': 'when will the <keyword> reach by',
                     'estimated': 'when is the <keyword> estimated to reach',
                     'estimate': 'when is the estimate year for <keyword>',
                     'increased': 'when will the <keyword> be increased to',
                     'increase': 'when will the <keyword> increase',
                     'increasing': 'when will the <keyword> be increasing to',
                     'surged': 'when will the <keyword> surged',
                     'surge': 'when will the <keyword> surge',
                     'surging': 'when will the <keyword> be surging to',
                     'expected': 'when is the <keyword> expected',
                     'growing': 'when is the <keyword> be growing to',
                     'grew': 'when did the <keyword> grow',
                     'grow': 'when will the <keyword> grow',
                     'expanded': 'when did the <keyword> expand',
                     'expand': 'when will the <keyword> expand',
                     'expanding': 'when is the <keyword> expanding to',
                     'forecast': 'when is the <keyword> forecasted to grow',
                     'expecting': 'when is the <keyword> expecting to reach by',
                     'expect': 'when is the <keyword> expected to reach by'

                     }

list1 = proj_value_dict.keys()
print(list(list1))